"""initial_schema

Revision ID: 7fc4c92b7acd
Revises: 
Create Date: 2026-08-29 23:53:02.868961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7fc4c92b7acd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repositories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('github_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=512), nullable=False),
    sa.Column('clone_url', sa.String(length=2048), nullable=False),
    sa.Column('default_branch', sa.String(length=255), nullable=False),
    sa.Column('owner_login', sa.String(length=255), nullable=False),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('github_access_token', sa.String(length=2048), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repositories_full_name'), 'repositories', ['full_name'], unique=True)
    op.create_index(op.f('ix_repositories_github_id'), 'repositories', ['github_id'], unique=True)
    op.create_table('scans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('scan_type', sa.Enum('REPO', 'PR', name='scan_type_enum'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='scan_status_enum'), nullable=False),
    sa.Column('pr_number', sa.Integer(), nullable=True),
    sa.Column('git_ref', sa.String(length=512), nullable=True),
    sa.Column('security_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('gate_result', sa.Enum('PASS', 'WARNING', 'BLOCK', name='gate_result_enum'), nullable=True),
    sa.Column('error_message', sa.String(length=4096), nullable=True),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('github_check_run_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scans_repository_id'), 'scans', ['repository_id'], unique=False)
    op.create_table('findings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scan_id', sa.UUID(), nullable=False),
    sa.Column('finding_key', sa.String(length=512), nullable=False),
    sa.Column('tool', sa.Enum('SEMGREP', 'GITLEAKS', 'TRIVY', name='finding_tool_enum'), nullable=False),
    sa.Column('finding_type', sa.String(length=255), nullable=False),
    sa.Column('severity', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFO', name='finding_severity_enum'), nullable=False),
    sa.Column('file_path', sa.String(length=2048), nullable=False),
    sa.Column('line_start', sa.Integer(), nullable=True),
    sa.Column('line_end', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('rule_id', sa.String(length=512), nullable=True),
    sa.Column('code_snippet', sa.Text(), nullable=True),
    sa.Column('raw_output', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_findings_finding_key'), 'findings', ['finding_key'], unique=False)
    op.create_index(op.f('ix_findings_scan_id'), 'findings', ['scan_id'], unique=False)
    op.create_index(op.f('ix_findings_severity'), 'findings', ['severity'], unique=False)
    op.create_table('policy_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scan_id', sa.UUID(), nullable=False),
    sa.Column('gate_result', sa.Enum('PASS', 'WARNING', 'BLOCK', name='gate_result_enum'), nullable=False),
    sa.Column('triggered_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('findings_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_results_scan_id'), 'policy_results', ['scan_id'], unique=True)
    op.create_table('repository_contexts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scan_id', sa.UUID(), nullable=False),
    sa.Column('languages', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('frameworks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('databases', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('authentication', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('file_tree_summary', sa.Text(), nullable=True),
    sa.Column('architecture_summary', sa.Text(), nullable=True),
    sa.Column('raw_context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repository_contexts_scan_id'), 'repository_contexts', ['scan_id'], unique=True)
    op.create_table('finding_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('finding_id', sa.UUID(), nullable=False),
    sa.Column('is_true_positive', sa.Boolean(), nullable=True),
    sa.Column('exploitability', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('impact', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('exposure', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('business_impact', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('risk_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('attack_scenario', sa.Text(), nullable=True),
    sa.Column('ai_explanation', sa.Text(), nullable=True),
    sa.Column('owasp_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cwe_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('security_recommendations', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finding_analyses_finding_id'), 'finding_analyses', ['finding_id'], unique=True)
    op.create_table('finding_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('finding_id', sa.UUID(), nullable=False),
    sa.Column('scan_id', sa.UUID(), nullable=False),
    sa.Column('history_status', sa.Enum('NEW', 'RECURRING', 'UNCHANGED', 'RESOLVED', name='history_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finding_history_finding_id'), 'finding_history', ['finding_id'], unique=False)
    op.create_index(op.f('ix_finding_history_scan_id'), 'finding_history', ['scan_id'], unique=False)
    op.create_table('remediation_suggestions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('finding_id', sa.UUID(), nullable=False),
    sa.Column('suggested_fix', sa.Text(), nullable=True),
    sa.Column('secure_coding_guidance', sa.Text(), nullable=True),
    sa.Column('fix_explanation', sa.Text(), nullable=True),
    sa.Column('validation_status', sa.Enum('NOT_RUN', 'PENDING', 'PASS', 'FAIL', name='validation_status_enum'), nullable=False),
    sa.Column('validation_log', sa.Text(), nullable=True),
    sa.Column('validation_celery_task_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_remediation_suggestions_finding_id'), 'remediation_suggestions', ['finding_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_remediation_suggestions_finding_id'), table_name='remediation_suggestions')
    op.drop_table('remediation_suggestions')
    op.drop_index(op.f('ix_finding_history_scan_id'), table_name='finding_history')
    op.drop_index(op.f('ix_finding_history_finding_id'), table_name='finding_history')
    op.drop_table('finding_history')
    op.drop_index(op.f('ix_finding_analyses_finding_id'), table_name='finding_analyses')
    op.drop_table('finding_analyses')
    op.drop_index(op.f('ix_repository_contexts_scan_id'), table_name='repository_contexts')
    op.drop_table('repository_contexts')
    op.drop_index(op.f('ix_policy_results_scan_id'), table_name='policy_results')
    op.drop_table('policy_results')
    op.drop_index(op.f('ix_findings_severity'), table_name='findings')
    op.drop_index(op.f('ix_findings_scan_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_finding_key'), table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_scans_repository_id'), table_name='scans')
    op.drop_table('scans')
    op.drop_index(op.f('ix_repositories_github_id'), table_name='repositories')
    op.drop_index(op.f('ix_repositories_full_name'), table_name='repositories')
    op.drop_table('repositories')
    # ### end Alembic commands ###
